// src/data/programs.ts
// AUTO-GENERATED BY LLM EXTRACTION
// Generated on: 2025

export type Program = {
  id: string;
  name: string;
  category: 'Pendidikan' | 'Kesehatan' | 'Teknologi' | 'Lingkungan' | 'Ekonomi Kreatif' | 'Pariwisata' | 'Pemberdayaan Masyarakat' | 'Infrastruktur' | 'Pertanian' | 'Kelautan';
  description: string;
  location: {
    lat: number;
    lng: number;
    address: string;
  };
  images: string[]; // URLs to images
  videoUrl?: string; // URL to a video (e.g., YouTube embed URL)
  detailsUrl: string; // URL for more detailed info, maybe Wikipedia
  year: number;
  status: 'Planned' | 'In Progress' | 'Completed';
};

export const programs: Program[] = [
  {
    "id": "p2m-2025-001",
    "name": "Pemberdayaan Masyarakat Desa Pulau Jemare",
    "category": "Teknologi",
    "description": "Program ini bertujuan untuk meningkatkan kualitas penerangan dan penyediaan air bersih di Pulau Jemare melalui penerapan teknologi tepat guna, seperti penerangan jalan umum dan sistem pompa air tenaga surya. Melalui kolaborasi dengan warga setempat, program ini berhasil memasang lampu jalan dan sistem pompa air yang diharapkan memberikan dampak positif pada kualitas hidup warga.",
    "location": {
      "lat": 1.0196577,
      "lng": 104.5698189,
      "address": "Pulau Jemare"
    },
    "images": [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2025,
    "status": "Completed"
  },
  {
    "id": "p2m-2025-002",
    "name": "Sosialisasi Strategi Pemasaran Digital Pasca Panen Hidroponik",
    "category": "Pendidikan",
    "description": "Program ini bertujuan untuk meningkatkan kapasitas petani muda generasi milenial dalam memasarkan produk pertanian hidroponik pasca panen secara digital melalui platform e-commerce TikTok. Melalui seminar edukasi dan pelatihan praktis, peserta dari SMAN 1 Pemali diberdayakan dalam strategi pemasaran digital dan penggunaan alat e-commerce.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "SMAN 1 Pemali"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2025,
    "status": "Completed"
  },
  {
    "id": "p2m-2025-003",
    "name": "Sosialisasi Bahaya JUDOL di SMKN 2 Sungailiat",
    "category": "Pendidikan",
    "description": "Program ini bertujuan untuk meningkatkan pemahaman siswa SMKN 2 Sungailiat tentang judi online dan dampaknya terhadap ekonomi, serta menumbuhkan kesadaran kritis dan sikap penolakan terhadap praktik judi online. Metode yang digunakan adalah sosialisasi dengan persiapan, pelaksanaan program, dan evaluasi melalui pre-test, post-test, dan kualitatif.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "SMKN 2 Sungailiat"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2025,
    "status": "Completed"
  },
  {
    "id": "p2m-2025-004",
    "name": "Pemasangan CCTV di Perumahan Rawan Pencuri",
    "category": "Kesehatan",
    "description": "Program ini bertujuan untuk meningkatkan keamanan di lingkungan perumahan dengan pemasangan sistem keamanan berupa CCTV. Metode meliputi survei lokasi, pemilihan jenis kamera, penempatan DVR, dan pengaturan perangkat lunak. Respon positif diterima dari pengurus RT dan masyarakat setempat.",
    "location": {
      "lat": 1.0490933,
      "lng": 103.9398514,
      "address": "Perumahan Fanindo, Tanjung Uncang, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2025,
    "status": "Completed"
  },
  {
    "id": "p2m-2025-005",
    "name": "Workshop K3 untuk Pelajar SMK",
    "category": "Kesehatan",
    "description": "Program ini bertujuan meningkatkan kesadaran, pengetahuan, dan praktik K3 di lingkungan kerja pelajar SMK Negeri 1 Bintan Utara untuk mengurangi risiko kecelakaan dan penyakit terkait pekerjaan. Workshop diselenggarakan untuk mengidentifikasi, mengevaluasi, dan mengendalikan risiko K3 di lingkungan kerja.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "SMK Negeri 1 Bintan Utara"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2025,
    "status": "Completed"
  },
  {
    "id": "p2m-2025-006",
    "name": "Sosialisasi Hidroponik di SMA Negeri 1 Pemali",
    "category": "Pendidikan",
    "description": "Program ini bertujuan untuk meningkatkan keterampilan siswa dalam membuat dan merawat hidroponik sederhana di SMAN 1 Pemali. Metode yang digunakan melibatkan sosialisasi dan pelatihan mengenai hidroponik sumbu. Kegiatan ini juga memberikan kesadaran tentang pentingnya memanfaatkan lahan sempit dan barang bekas untuk budidaya tanaman melalui hidroponik.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "SMA Negeri 1 Pemali"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2025,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-007",
    "name": "Implementasi Media Promosi Wisata Pulau Mubut",
    "category": "Pariwisata",
    "description": "Studi ini bertujuan untuk membantu pengelola wisata Pulau Mubut dalam memanfaatkan website sebagai media promosi wisata. Metode meliputi tahap persiapan, pengembangan konten website, implementasi sebagai media promosi, dan evaluasi kepuasan pengguna website.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Pulau Mubut"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2024-008",
    "name": "Potensi Desa Wisata Pulau Galang",
    "category": "Pariwisata",
    "description": "Penelitian ini bertujuan untuk mengidentifikasi potensi pariwisata Pulau Galang dengan pendekatan studi kasus. Hasil penelitian menunjukkan bahwa Pulau Galang memiliki potensi wisata yang signifikan namun masih memerlukan peningkatan infrastruktur dan pemberdayaan ekonomi.",
    "location": {
      "lat": 0.7388,
      "lng": 104.2343,
      "address": "Pulau Galang"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "http://ejurnal.umri.ac.id/index.php/jae",
    "year": 2024,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-009",
    "name": "Perancangan Visual Branding Wisata Pulau Mubut Darat",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk merancang visual branding untuk wisata Pulau Mubut Darat dengan menggunakan metode Branding Process. Melalui riset dan desain identitas lokal, program ini bertujuan untuk memperkuat identitas wisata dan mempromosikan kembali pariwisata di tengah pandemi. Metode perancangan melibatkan tahapan penelitian, strategi, desain identitas, menciptakan sentuhan pokok, dan mengelola aset.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Pulau Mubut Darat"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-010",
    "name": "Pemberdayaan Masyarakat Pulau Akar",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk memberdayakan masyarakat Pulau Akar di Batam melalui pengajaran bahasa Inggris, pemasaran, dan teknologi digital agar mampu berkomunikasi dengan wisatawan asing, mempromosikan destinasi pariwisata, serta menggunakan teknologi digital sebagai media publikasi. Metode yang diterapkan meliputi perkenalan diri, presentasi, diskusi, dan praktek.",
    "location": {
      "lat": 2.5031589,
      "lng": 109.0146598,
      "address": "Kampung Pulau Akar, Kelurahan Setokok, Kecamatan Bulang, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2020-011",
    "name": "Pembinaan Branding Kupat Tahu Padalarang",
    "category": "Pariwisata",
    "description": "Program kemitraan masyarakat ini bertujuan mengembangkan usaha kuliner Kupat Tahu Padalarang di Kecamatan Batujajar, Jawa Barat dengan membangun identitas merek, personal branding, pelayanan prima, dan komunikasi pelanggan yang baik. Survey dilakukan untuk mengevaluasi kesadaran merek, kondisi usaha, dan kepuasan pelanggan sebelum dan sesudah program dijalankan.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kecamatan Batujajar"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2020,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-012",
    "name": "Keselamatan & Kesehatan Kerja Kapal Kayu",
    "category": "Kesehatan",
    "description": "Studi ini bertujuan untuk meningkatkan kesadaran akan keselamatan dan kesehatan kerja dalam proses perbaikan kapal kayu di Daerah Pasir Panjang. Metode yang digunakan meliputi penyuluhan dan langkah-langkah aman dalam melakukan perbaikan kapal.",
    "location": {
      "lat": 0.8256,
      "lng": 104.2691,
      "address": "Daerah Pasir Panjang"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-013",
    "name": "Pemanfaatan Hasil Tangkap Ikan di Kampung Rempang Cate",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk mengenalkan keindahan dan hasil laut di Pantai Pasir Panjang kepada masyarakat melalui pelatihan pembuatan pempek. Pelatihan dilakukan di Kampung Pesisir Pasir Panjang, dengan hasil survei menunjukkan peningkatan pengetahuan dan keterampilan masyarakat sekaligus potensi pariwisata di daerah tersebut.",
    "location": {
      "lat": 0.8256,
      "lng": 104.2691,
      "address": "Kampung Pesisir Pasir Panjang, Kelurahan Pasir Panjang, Kecamatan Rempang Cate, Kota Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-014",
    "name": "Pelatihan Bahasa Inggris untuk Masyarakat Hinterland",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk melatih masyarakat Rempang Cate dalam berkomunikasi Bahasa Inggris sebagai tuan rumah desa wisata Pasir Panjang. Melalui pelatihan ini diharapkan kawasan Pasir Panjang dapat menarik lebih banyak wisatawan. Metode pelatihan dilakukan dengan memberikan materi latihan percakapan sederhana.",
    "location": {
      "lat": 0.8256,
      "lng": 104.2691,
      "address": "Kelurahan Pasir Panjang, Kecamatan Rempang Cate, Kota Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2020-015",
    "name": "Pemberdayaan Masyarakat Nelayan melalui Inkubator Bisnis",
    "category": "Pemberdayaan Masyarakat",
    "description": "Program ini bertujuan untuk meningkatkan perekonomian masyarakat nelayan Kampung Tua Nongsa melalui pelatihan konsultasi dan pendampingan kewirausahaan serta inkubator bisnis. Metode pelaksanaan kegiatan menggunakan pre dan post test. Output kegiatan meliputi menciptakan produk baru, mengembangkan keterampilan masyarakat, dan memenuhi tri darma perguruan tinggi.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kampung Tua Teluk Mata Ikan Nongsa"
    },
    "images": [
      "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=800",
      "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2020,
    "status": "Completed"
  },
  {
    "id": "p2m-2020-016",
    "name": "Penentuan Arah Kiblat di Kampung Pasir Panjang",
    "category": "Pendidikan",
    "description": "Kegiatan pengabdian ini bertujuan untuk mensosialisasikan metode penentuan arah kiblat secara teliti dengan teknologi survei pemetaan, yaitu Total Station, sekaligus bersama-sama dengan masyarakat setempat melakukan kegiatan pengukuran di lapangan. Dilakukan dalam dua tahap, yaitu persiapan dan pelaksanaan di lapangan dengan menggunakan prinsip perhitungan segitiga bola dalam ilmu Matematika Geodesi.",
    "location": {
      "lat": 0.8256,
      "lng": 104.2691,
      "address": "Kampung Pasir Panjang"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2020,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-017",
    "name": "Pelatihan Peta Kelurahan Galang Batam",
    "category": "Pendidikan",
    "description": "Program ini bertujuan untuk memberikan pelatihan dalam pembuatan peta desa di Sembulang, Batam. Kegiatan meliputi penggunaan GPS handheld, deliniasi citra Google Earth, dan dokumentasi informasi geospasial. Pelatihan dilaksanakan pada Agustus 2019 dengan peserta dari perangkat Kecamatan Galang dan perangkat kelurahan.",
    "location": {
      "lat": 0.8541,
      "lng": 104.2404,
      "address": "Sembulang, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2020-018",
    "name": "Mini House Destilator Air Laut",
    "category": "Kesehatan",
    "description": "Program ini bertujuan untuk menyediakan stok air bersih dengan menggunakan mini-house destilator air laut di Pantai Setokok, Batam. Alat ini merupakan alternatif sederhana, ekonomis, dan ramah lingkungan untuk menyuling air laut menjadi air tawar, membantu masyarakat pesisir dalam memenuhi kebutuhan air bersih.",
    "location": {
      "lat": 0.92335,
      "lng": 104.06094,
      "address": "Pantai Setokok, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2020,
    "status": "Completed"
  },
  {
    "id": "p2m-2021-019",
    "name": "Pemetaan Partisipatif Objek Wisata Pulau Setokok",
    "category": "Pariwisata",
    "description": "Studi ini bertujuan untuk mengembangkan potensi pariwisata di Pulau Setokok melalui pemetaan partisipatif objek wisata dan fasilitas pendukungnya. Metode yang digunakan adalah pemetaan partisipatif yang kemudian dipublikasikan dalam bentuk WebGIS untuk meningkatkan kesadaran masyarakat akan potensi pariwisata di pulau tersebut.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kelurahan Pulau Setokok"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2021,
    "status": "Completed"
  },
  {
    "id": "p2m-2021-020",
    "name": "Panel Surya untuk Pencuci Tangan di Pasar Mitra Raya",
    "category": "Teknologi",
    "description": "Program ini bertujuan untuk memasang alat pencuci tangan otomatis di Pasar Mitra Raya Kota Batam dengan sumber energi listrik alternatif dari panel surya. Dengan demikian, diharapkan dapat meningkatkan kebersihan dan efisiensi dalam mencuci tangan di tempat umum.",
    "location": {
      "lat": 1.1204732,
      "lng": 104.0430552,
      "address": "Pasar Mitra Raya, Kota Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2021,
    "status": "Completed"
  },
  {
    "id": "p2m-2021-021",
    "name": "Pelatihan Spreadsheet di SMK Muhammadiyah Adiwerna",
    "category": "Pendidikan",
    "description": "Pelatihan ini bertujuan untuk meningkatkan pengetahuan dan penguasaan guru SMK Muhammadiyah Adiwerna dalam menggunakan program aplikasi Spreadsheet untuk mendukung pembelajaran akuntansi. Program dilaksanakan sebagai respons terhadap kebutuhan kurikulum 2013 yang menekankan penggunaan teknologi dalam pendidikan.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Desa Adiwerna, Kabupaten Tegal"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2021,
    "status": "Completed"
  },
  {
    "id": "p2m-2021-022",
    "name": "Intensifikasi Jalur Transportasi Nelayan di Kel. Sembulang",
    "category": "Kelautan",
    "description": "Program ini bertujuan untuk meningkatkan jalur transportasi nelayan melalui sosialisasi rute pelayaran efektif berbasis medan di Kelurahan Sembulang. Dengan menganalisis medan kompleks, program ini memberikan pemahaman kepada nelayan tentang jalur transportasi laut terbaik sambil meminimalisir dampak negatif terhadap lingkungan.",
    "location": {
      "lat": 0.8541,
      "lng": 104.2404,
      "address": "Kelurahan Sembulang"
    },
    "images": [
      "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=800",
      "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2021,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-023",
    "name": "Evaluasi Air Bersih & Listrik Surya",
    "category": "Kesehatan",
    "description": "Studi evaluasi penyediaan air bersih dengan sumber listrik tenaga surya di Desa Pasir Panjang, Rempang. Kegiatan meliputi pemberian peralatan dan pemasangan pompa air dengan sumber listrik mandiri dari sel surya 100WP. Hasil penelitian menunjukkan perbaikan sistem instalasi kelistrikan dengan mengubah diameter kabel distribusi arus.",
    "location": {
      "lat": 0.8541,
      "lng": 104.2404,
      "address": "Desa Pasir Panjang, Pulau Rempang"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2021-024",
    "name": "Augmented Reality Penanganan Kebakaran Hutan",
    "category": "Kesehatan",
    "description": "Program ini menggunakan augmented reality sebagai media pelatihan untuk penanganan kebakaran hutan bagi warga Desa Pasir Panjang, Batam. Tujuannya adalah meningkatkan pengetahuan dan keterampilan warga dalam menghadapi bencana kebakaran. Metode pelatihan dilakukan melalui simulasi penggunaan alat pemadam api dengan aplikasi berbasis augmented reality.",
    "location": {
      "lat": 0.8256,
      "lng": 104.2691,
      "address": "Desa Pasir Panjang, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2021,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-025",
    "name": "Pengembangan Kewirausahaan Syariah di Kopontren",
    "category": "Ekonomi Kreatif",
    "description": "Program ini bertujuan untuk meningkatkan keterampilan manajerial dan pemanfaatan teknologi informasi dalam pencatatan keuangan digital di Kopontren Daarul Rahman. Metode pelaksanaan meliputi wawancara, ceramah, praktik, dan diskusi pelatihan menggunakan aplikasi teknologi informasi.",
    "location": {
      "lat": 0.8493748,
      "lng": 104.2619318,
      "address": "Cipedak, Jagakarsa, Jakarta Selatan"
    },
    "images": [
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800",
      "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-026",
    "name": "Penguatan Kecerdasan Linguistik di Desa Wisata Pulau Mubut",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk meningkatkan kecerdasan linguistik masyarakat Desa Mubut agar mampu berkomunikasi dalam bahasa Inggris bisnis guna mendukung pengembangan Desa Wisata Pulau Mubut. Metode yang dilakukan meliputi pelatihan offline, pemberian buku saku, dan video simulasi.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Desa Mubut, Pulau Mubut"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-027",
    "name": "Perbaikan Listrik Pulau Mubud Darat",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk meningkatkan infrastruktur listrik dan penerangan di Pulau Mubud Darat, sebuah destinasi wisata di Kota Batam. Dengan menggunakan panel surya dan lampu LED, program ini juga menciptakan ikon wisata baru untuk menarik pengunjung.",
    "location": {
      "lat": 1.0196577,
      "lng": 104.5698189,
      "address": "Pulau Mubud Darat"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-028",
    "name": "Studi Kelayakan Rute Pelayaran Batam Marine Ambulance",
    "category": "Kesehatan",
    "description": "Program ini bertujuan untuk menghasilkan peta batimetri guna memastikan rute pelayaran kapal ambulans yang aman dan efisien di Kecamatan Belakang Padang, Batam. Kolaborasi antara LAZ Batam, Politeknik Negeri Batam, dan RS Awal Bross dilakukan untuk mewujudkan kapal ambulans generasi kedua.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kecamatan Belakang Padang"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-029",
    "name": "Plang Denah Lokasi Pulau Mubut Darat",
    "category": "Pariwisata",
    "description": "Program ini bertujuan untuk meningkatkan promosi dan daya tarik wisata di Pulau Mubut Darat melalui pembuatan plang informasi denah lokasi atau POI. Metode meliputi pemetaan lokasi bangunan dan fasilitas serta pembuatan plang informasi. Diharapkan plang ini dapat menjadi ikon foto wisata yang mempromosikan dan meningkatkan jumlah wisatawan yang berkunjung.",
    "location": {
      "lat": 0.8541,
      "lng": 104.2404,
      "address": "Desa Mubut Darat, Kecamatan Sembulang, Kota Batam, Kepulauan Riau"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-030",
    "name": "Perspektif Masyarakat Lokal di Mubut Darat",
    "category": "Lingkungan",
    "description": "Studi ini bertujuan untuk menggali pandangan masyarakat lokal terkait pembangunan desa wisata dan dampak kerusakan lingkungan yang menyertainya di Mubut Darat. Metode penelitian melibatkan wawancara dengan pengelola pantai dan awak media serta penggunaan kuesioner.",
    "location": {
      "lat": 1.0196577,
      "lng": 104.5698189,
      "address": "Mubut Darat"
    },
    "images": [
      "https://images.unsplash.com/photo-1542601906990-b4d3fb7d5b43?w=800",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-031",
    "name": "Perancangan Sistem Ecobrick di Pulau Mubut Darat",
    "category": "Lingkungan",
    "description": "Program ini bertujuan untuk merancang dan membuat ecobrick dari sampah plastik guna mengatasi permasalahan sampah domestik di komunitas pesisir di Pulau Mubut Darat. Metode meliputi persiapan alat dan bahan, survei lokasi sampah, penyuluhan, pembuatan ecobrick, evaluasi, dan pemantauan.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Pulau Mubut Darat"
    },
    "images": [
      "https://images.unsplash.com/photo-1542601906990-b4d3fb7d5b43?w=800",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2021-032",
    "name": "Website Promosi Wisata Pulau Mubut",
    "category": "Pariwisata",
    "description": "Kegiatan ini bertujuan untuk membangun dan menerapkan website wisata Pulau Mubut sebagai media promosi. Metode pelaksanaan melibatkan observasi, sosialisasi, dan pelatihan pengguna secara aktif.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Pulau Mubut Darat, Kecamatan Galang, Kota Batam, Kepulauan Riau"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2021,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-033",
    "name": "Perawatan Kapal Ambulans Laut",
    "category": "Kesehatan",
    "description": "Program ini bertujuan untuk melakukan perawatan rutin terhadap kapal ambulans laut Batam Marine Ambulance guna memastikan fungsi sistem kapal berjalan dengan baik sebagai sarana transportasi medis. Kegiatan perawatan dilakukan untuk memperbaiki dan mempertahankan fungsi kapal agar layanan transportasi medis berjalan lancar.",
    "location": {
      "lat": 1.0196577,
      "lng": 104.5698189,
      "address": "Pulau Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2019-034",
    "name": "Pemberdayaan Masyarakat Kampung Rempang",
    "category": "Pemberdayaan Masyarakat",
    "description": "Program ini bertujuan untuk memberdayakan masyarakat Kampung Rempang Cate melalui pelatihan pemasaran digital untuk produk unggulan seperti kerupuk ikan, kue bangkit, kerupuk paru, dan empek-empek. Dengan memanfaatkan media sosial, program ini bertujuan meningkatkan ekonomi masyarakat dan mengurangi ketidakpastian penjualan produk.",
    "location": {
      "lat": 2.5031589,
      "lng": 109.0146598,
      "address": "Kampung Rempang Cate, Kecamatan Galang, Kota Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=800",
      "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2019,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-035",
    "name": "Perancangan Sistem Informasi Akuntansi Penjualan",
    "category": "Teknologi",
    "description": "Program ini bertujuan untuk merancang Sistem Informasi Akuntansi Penjualan menggunakan Program Microsoft Visual Basic 6.0 pada PD Mie Ayam Berkah. Metode yang digunakan adalah wawancara dan tinjauan langsung terhadap sistem pencatatan penjualan yang ada.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "PD Mie Ayam Berkah"
    },
    "images": [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-036",
    "name": "Plang Denah Lokasi Penangkapan Ikan Nongsa Batam",
    "category": "Teknologi",
    "description": "Program ini bertujuan untuk memberikan pemahaman dan keterampilan kepada masyarakat pesisir dan pulau kecil di Nongsa, Batam, dalam menentukan dan memetakan daerah penangkapan ikan berbasis teknologi bawah air. Melalui pengembangan IPTEk, program ini membantu masyarakat pesisir dalam menentukan spot penangkapan ikan untuk meningkatkan kemandirian ekonomi mereka.",
    "location": {
      "lat": 0.6772011,
      "lng": 104.3041216,
      "address": "Teluk Mata Ikan, Nongsa, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-037",
    "name": "Pelatihan Media Promosi Desa Wisata Pulau Mubut",
    "category": "Pariwisata",
    "description": "Pelatihan ini bertujuan untuk mengoptimalkan media promosi sosial, khususnya Facebook, bagi pengelola Desa Wisata Pulau Mubut. Dengan demikian, diharapkan Desa Wisata Pulau Mubut dapat lebih dikenal dan dikunjungi oleh masyarakat luas.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Desa Wisata Pulau Mubut"
    },
    "images": [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-038",
    "name": "Rancang Bangun Kerangka Tanaman Hidroponik",
    "category": "Pertanian",
    "description": "Proyek pilot hidroponik di Politeknik Negeri Batam bertujuan mendukung gerakan 'menanam sendiri makananmu' untuk mengurangi pengangguran, meningkatkan ketahanan pangan, dan pola hidup sehat. Kegiatan ini melibatkan pembuatan kerangka bangunan tanaman hidroponik efisien sebagai prototipe yang dapat dimanfaatkan oleh masyarakat luas.",
    "location": {
      "lat": 1.1184,
      "lng": 104.0485,
      "address": "Politeknik Negeri Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800",
      "https://images.unsplash.com/photo-1625246333195-5819acf42587?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-039",
    "name": "Pendampingan Laporan Keuangan Pondok Pesantren",
    "category": "Pendidikan",
    "description": "Kegiatan pengabdian ini bertujuan untuk menyusun laporan keuangan dan pajak Pondok Pesantren Baitul Qur’an berbasis Excel, dengan metode pendampingan dan pengembangan aplikasi Excel. Lokasi kegiatan berada di Tanjung Buntung, Kecamatan Bengkong, Kota Batam, Kepulauan Riau.",
    "location": {
      "lat": 1.1687351,
      "lng": 104.0340261,
      "address": "Tanjung Buntung, Kecamatan Bengkong, Kota Batam, Kepulauan Riau"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-040",
    "name": "Pelatihan Website Pulau Mubut",
    "category": "Pendidikan",
    "description": "Program ini bertujuan untuk melatih dan mendampingi pengelola Desa Pulau Mubut dalam mengoptimalkan website promosi mereka menggunakan teknik Search Engine Optimization (SEO). Pelatihan dilakukan dengan melibatkan praktisi SEO dan mahasiswa Project Based Learning (PBL). Evaluasi dilakukan terhadap kemampuan pengelola dalam mengoptimasi website dan peningkatan jumlah pengunjung setelah optimalisasi.",
    "location": {
      "lat": 0.81975,
      "lng": 104.2816,
      "address": "Desa Pulau Mubut"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2024-041",
    "name": "Penetapan Batas Wilayah RT & RW di Kelurahan Sembulang",
    "category": "Pemberdayaan Masyarakat",
    "description": "Program ini bertujuan untuk melakukan pemetaan batas wilayah RT & RW di Kelurahan Sembulang menggunakan metode partisipatif. Peta wilayah ini penting untuk menciptakan tertib administrasi dan kepastian hukum, serta meminimalisir konflik batas. Metode kartometrik digunakan untuk menetapkan batas wilayah sesuai regulasi Badan Informasi Geospasial.",
    "location": {
      "lat": 0.8541,
      "lng": 104.2404,
      "address": "Kelurahan Sembulang"
    },
    "images": [
      "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=800",
      "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2024,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-042",
    "name": "Pembuatan Peta Foto Udara di Tanjung Riau",
    "category": "Pendidikan",
    "description": "Studi dan survei dalam bentuk Pembelajaran Berbasis Proyek (PBL) dilakukan oleh mahasiswa Politeknik Negeri Batam dalam pengabdian masyarakat di Tanjung Riau, Kota Batam. Kegiatan ini melibatkan pembuatan peta foto udara menggunakan drone DJI Phantom 4 RTK.",
    "location": {
      "lat": 1.1671271,
      "lng": 104.028717,
      "address": "Kelurahan Tanjung Riau, Kecamatan Sekupang, Kota Batam, Provinsi Kepulauan Riau"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-043",
    "name": "Pengukur Nutrisi Tanah Portabel di Pulau Setokok",
    "category": "Pertanian",
    "description": "Program ini bertujuan untuk mengembangkan alat pengukur nutrisi tanah portabel sebagai dukungan dalam program pengembangan lahan pertanian. Melalui kerjasama dengan Kelompok Tani Maju Mandiri di Pulau Setokok, program ini telah mencapai tahap pengembangan alat pengukur nutrisi tanah portabel untuk pengujian laboratorium.",
    "location": {
      "lat": 1.0196577,
      "lng": 104.5698189,
      "address": "Pulau Setokok"
    },
    "images": [
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800",
      "https://images.unsplash.com/photo-1625246333195-5819acf42587?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-044",
    "name": "Pembuatan Website Media Promosi dan Pemasaran Ikan",
    "category": "Pendidikan",
    "description": "Program ini bertujuan membantu kelompok nelayan mengelola konten website sebagai media promosi dan pemasaran produk hasil pengolahan ikan. Melalui pelatihan dan pendampingan, kelompok nelayan dapat mengembangkan konten yang menarik dan informatif untuk menjangkau pasar lokal dan regional.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kelurahan Batu Besar, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-045",
    "name": "Pengembangan SI Kelurahan Website",
    "category": "Teknologi",
    "description": "Penelitian ini bertujuan untuk mengembangkan dan mengimplementasikan Sistem Informasi Kelurahan berbasis website di Kelurahan Pulau Buluh, Kota Batam. Metode pengabdian kepada masyarakat dilakukan dengan merancang aplikasi berbasis OpenSID untuk membantu pengelolaan arsip dan data administrasi kependudukan.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kelurahan Pulau Buluh, Kecamatan Bulang, Kota Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  },
  {
    "id": "p2m-2024-046",
    "name": "Pelatihan Mesin Laser Cutting di SMKN 9 Batam",
    "category": "Pendidikan",
    "description": "Kegiatan pengabdian ini bertujuan untuk meningkatkan keterampilan siswa SMKN 9 Batam dalam menggunakan mesin Laser cutting untuk fabrikasi produk berdasarkan desain mereka. Kegiatan ini membantu siswa memperluas pembelajaran desain mereka ke proses fabrikasi, dengan hasil berupa souvenir gantungan kunci.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "SMKN 9 Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2024,
    "status": "Completed"
  },
  {
    "id": "p2m-2024-047",
    "name": "Pengembangan Aplikasi Microlearning di SMA IT Ulil Albab Batam",
    "category": "Pendidikan",
    "description": "Program ini bertujuan untuk mengembangkan media pembelajaran microlearning berbasis mobile di SMA IT Ulil Albab Batam dengan metode persiapan, pelaksanaan, dan tahap akhir. Hasil uji coba aplikasi menunjukkan kepuasan pengguna sebesar 87,52% dan kepuasan mitra sebesar 90,3%.",
    "location": {
      "lat": 1.0497484,
      "lng": 103.9563447,
      "address": "Kelurahan Bukit Tempayan, Kecamatan Batu Aji, Kota Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2024,
    "status": "Completed"
  },
  {
    "id": "p2m-2022-048",
    "name": "Pembangunan Bilik Pelindung Mesin Pembangkit Listrik",
    "category": "Teknologi",
    "description": "Program ini bertujuan untuk membangun bilik pelindung mesin pembangkit listrik di Kelurahan Rempang Cate sebagai solusi terhadap kesulitan penyediaan air bersih. Metode yang digunakan adalah memanfaatkan pompa air dengan tenaga listrik dari mesin pembangkit portabel berbasis teknologi water lifting.",
    "location": {
      "lat": 0.8493748,
      "lng": 104.2619318,
      "address": "Kelurahan Rempang Cate"
    },
    "images": [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2022,
    "status": "Completed"
  },
  {
    "id": "p2m-2023-049",
    "name": "Website Media Promosi Ikan Kel. Batu Besar, Batam",
    "category": "Pendidikan",
    "description": "Program ini bertujuan membantu kelompok nelayan mengelola konten website sebagai media promosi dan pemasaran produk hasil pengolahan ikan. Melalui pelatihan dan pendampingan, kelompok nelayan belajar teknik penulisan konten efektif dan penggunaan alat digital untuk meningkatkan visibilitas website mereka.",
    "location": {
      "lat": 1.1030815,
      "lng": 104.0383696,
      "address": "Kelurahan Batu Besar, Batam"
    },
    "images": [
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800"
    ],
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "detailsUrl": "https://jurnal.polibatam.ac.id",
    "year": 2023,
    "status": "Completed"
  }
];

// All 10 P2M categories (static list to show all, even if no programs exist yet)
export const categories = [
  'Pendidikan',
  'Kesehatan',
  'Teknologi',
  'Lingkungan',
  'Ekonomi Kreatif',
  'Pariwisata',
  'Pemberdayaan Masyarakat',
  'Infrastruktur',
  'Pertanian',
  'Kelautan',
];

// Dynamically extract unique years
export const years = [...new Set(programs.map(p => p.year))].sort((a, b) => a - b);

// Dynamically extract unique statuses
export const statuses = [...new Set(programs.map(p => p.status))];
